// Generated by gencpp from file demops3/AddTwoInts.msg
// DO NOT EDIT!


#ifndef DEMOPS3_MESSAGE_ADDTWOINTS_H
#define DEMOPS3_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <demops3/AddTwoIntsRequest.h>
#include <demops3/AddTwoIntsResponse.h>


namespace demops3
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace demops3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::demops3::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::demops3::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::demops3::AddTwoInts > {
  static const char* value()
  {
    return "demops3/AddTwoInts";
  }

  static const char* value(const ::demops3::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::demops3::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::demops3::AddTwoInts > 
template<>
struct MD5Sum< ::demops3::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::demops3::AddTwoInts >::value();
  }
  static const char* value(const ::demops3::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::demops3::AddTwoIntsRequest> should match 
// service_traits::DataType< ::demops3::AddTwoInts > 
template<>
struct DataType< ::demops3::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::demops3::AddTwoInts >::value();
  }
  static const char* value(const ::demops3::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::demops3::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::demops3::AddTwoInts > 
template<>
struct MD5Sum< ::demops3::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::demops3::AddTwoInts >::value();
  }
  static const char* value(const ::demops3::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::demops3::AddTwoIntsResponse> should match 
// service_traits::DataType< ::demops3::AddTwoInts > 
template<>
struct DataType< ::demops3::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::demops3::AddTwoInts >::value();
  }
  static const char* value(const ::demops3::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEMOPS3_MESSAGE_ADDTWOINTS_H
