; Auto-generated. Do not edit!


(cl:in-package turtlebot_arm_object_manipulation-msg)


;//! \htmlinclude MoveToTargetFeedback.msg.html

(cl:defclass <MoveToTargetFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass MoveToTargetFeedback (<MoveToTargetFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveToTargetFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveToTargetFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name turtlebot_arm_object_manipulation-msg:<MoveToTargetFeedback> is deprecated: use turtlebot_arm_object_manipulation-msg:MoveToTargetFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveToTargetFeedback>) ostream)
  "Serializes a message object of type '<MoveToTargetFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveToTargetFeedback>) istream)
  "Deserializes a message object of type '<MoveToTargetFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveToTargetFeedback>)))
  "Returns string type for a message object of type '<MoveToTargetFeedback>"
  "turtlebot_arm_object_manipulation/MoveToTargetFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveToTargetFeedback)))
  "Returns string type for a message object of type 'MoveToTargetFeedback"
  "turtlebot_arm_object_manipulation/MoveToTargetFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveToTargetFeedback>)))
  "Returns md5sum for a message object of type '<MoveToTargetFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveToTargetFeedback)))
  "Returns md5sum for a message object of type 'MoveToTargetFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveToTargetFeedback>)))
  "Returns full string definition for message of type '<MoveToTargetFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveToTargetFeedback)))
  "Returns full string definition for message of type 'MoveToTargetFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveToTargetFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveToTargetFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveToTargetFeedback
))
