; Auto-generated. Do not edit!


(cl:in-package turtlebot_arm_object_manipulation-msg)


;//! \htmlinclude MoveToTargetResult.msg.html

(cl:defclass <MoveToTargetResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass MoveToTargetResult (<MoveToTargetResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveToTargetResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveToTargetResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name turtlebot_arm_object_manipulation-msg:<MoveToTargetResult> is deprecated: use turtlebot_arm_object_manipulation-msg:MoveToTargetResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveToTargetResult>) ostream)
  "Serializes a message object of type '<MoveToTargetResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveToTargetResult>) istream)
  "Deserializes a message object of type '<MoveToTargetResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveToTargetResult>)))
  "Returns string type for a message object of type '<MoveToTargetResult>"
  "turtlebot_arm_object_manipulation/MoveToTargetResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveToTargetResult)))
  "Returns string type for a message object of type 'MoveToTargetResult"
  "turtlebot_arm_object_manipulation/MoveToTargetResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveToTargetResult>)))
  "Returns md5sum for a message object of type '<MoveToTargetResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveToTargetResult)))
  "Returns md5sum for a message object of type 'MoveToTargetResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveToTargetResult>)))
  "Returns full string definition for message of type '<MoveToTargetResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# result definition~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveToTargetResult)))
  "Returns full string definition for message of type 'MoveToTargetResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# result definition~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveToTargetResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveToTargetResult>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveToTargetResult
))
