; Auto-generated. Do not edit!


(cl:in-package turtlebot_arm_object_manipulation-msg)


;//! \htmlinclude MoveToTargetGoal.msg.html

(cl:defclass <MoveToTargetGoal> (roslisp-msg-protocol:ros-message)
  ((target_type
    :reader target_type
    :initarg :target_type
    :type cl:fixnum
    :initform 0)
   (named_target
    :reader named_target
    :initarg :named_target
    :type cl:string
    :initform ""))
)

(cl:defclass MoveToTargetGoal (<MoveToTargetGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveToTargetGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveToTargetGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name turtlebot_arm_object_manipulation-msg:<MoveToTargetGoal> is deprecated: use turtlebot_arm_object_manipulation-msg:MoveToTargetGoal instead.")))

(cl:ensure-generic-function 'target_type-val :lambda-list '(m))
(cl:defmethod target_type-val ((m <MoveToTargetGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader turtlebot_arm_object_manipulation-msg:target_type-val is deprecated.  Use turtlebot_arm_object_manipulation-msg:target_type instead.")
  (target_type m))

(cl:ensure-generic-function 'named_target-val :lambda-list '(m))
(cl:defmethod named_target-val ((m <MoveToTargetGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader turtlebot_arm_object_manipulation-msg:named_target-val is deprecated.  Use turtlebot_arm_object_manipulation-msg:named_target instead.")
  (named_target m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<MoveToTargetGoal>)))
    "Constants for message type '<MoveToTargetGoal>"
  '((:JOINT_STATE . 1)
    (:POSE_TARGET . 2)
    (:NAMED_TARGET . 3))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'MoveToTargetGoal)))
    "Constants for message type 'MoveToTargetGoal"
  '((:JOINT_STATE . 1)
    (:POSE_TARGET . 2)
    (:NAMED_TARGET . 3))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveToTargetGoal>) ostream)
  "Serializes a message object of type '<MoveToTargetGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'target_type)) ostream)
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'named_target))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'named_target))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveToTargetGoal>) istream)
  "Deserializes a message object of type '<MoveToTargetGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'target_type)) (cl:read-byte istream))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'named_target) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'named_target) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveToTargetGoal>)))
  "Returns string type for a message object of type '<MoveToTargetGoal>"
  "turtlebot_arm_object_manipulation/MoveToTargetGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveToTargetGoal)))
  "Returns string type for a message object of type 'MoveToTargetGoal"
  "turtlebot_arm_object_manipulation/MoveToTargetGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveToTargetGoal>)))
  "Returns md5sum for a message object of type '<MoveToTargetGoal>"
  "a0450d6732c71ca58c4402334c28860d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveToTargetGoal)))
  "Returns md5sum for a message object of type 'MoveToTargetGoal"
  "a0450d6732c71ca58c4402334c28860d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveToTargetGoal>)))
  "Returns full string definition for message of type '<MoveToTargetGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint8 JOINT_STATE  = 1~%uint8 POSE_TARGET  = 2~%uint8 NAMED_TARGET = 3~%~%# goal definition~%uint8 target_type~%~%# TODO  sensor_msgs/JointState joint_state~%# TODO  geometry_msgs/PoseStamped pose_target~%string named_target~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveToTargetGoal)))
  "Returns full string definition for message of type 'MoveToTargetGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint8 JOINT_STATE  = 1~%uint8 POSE_TARGET  = 2~%uint8 NAMED_TARGET = 3~%~%# goal definition~%uint8 target_type~%~%# TODO  sensor_msgs/JointState joint_state~%# TODO  geometry_msgs/PoseStamped pose_target~%string named_target~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveToTargetGoal>))
  (cl:+ 0
     1
     4 (cl:length (cl:slot-value msg 'named_target))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveToTargetGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveToTargetGoal
    (cl:cons ':target_type (target_type msg))
    (cl:cons ':named_target (named_target msg))
))
