; Auto-generated. Do not edit!


(cl:in-package turtlebot_arm_object_manipulation-msg)


;//! \htmlinclude ObjectDetectionResult.msg.html

(cl:defclass <ObjectDetectionResult> (roslisp-msg-protocol:ros-message)
  ((obj_names
    :reader obj_names
    :initarg :obj_names
    :type (cl:vector cl:string)
   :initform (cl:make-array 0 :element-type 'cl:string :initial-element "")))
)

(cl:defclass ObjectDetectionResult (<ObjectDetectionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ObjectDetectionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ObjectDetectionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name turtlebot_arm_object_manipulation-msg:<ObjectDetectionResult> is deprecated: use turtlebot_arm_object_manipulation-msg:ObjectDetectionResult instead.")))

(cl:ensure-generic-function 'obj_names-val :lambda-list '(m))
(cl:defmethod obj_names-val ((m <ObjectDetectionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader turtlebot_arm_object_manipulation-msg:obj_names-val is deprecated.  Use turtlebot_arm_object_manipulation-msg:obj_names instead.")
  (obj_names m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ObjectDetectionResult>) ostream)
  "Serializes a message object of type '<ObjectDetectionResult>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'obj_names))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((__ros_str_len (cl:length ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) ele))
   (cl:slot-value msg 'obj_names))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ObjectDetectionResult>) istream)
  "Deserializes a message object of type '<ObjectDetectionResult>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'obj_names) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'obj_names)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:aref vals i) __ros_str_idx) (cl:code-char (cl:read-byte istream))))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ObjectDetectionResult>)))
  "Returns string type for a message object of type '<ObjectDetectionResult>"
  "turtlebot_arm_object_manipulation/ObjectDetectionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ObjectDetectionResult)))
  "Returns string type for a message object of type 'ObjectDetectionResult"
  "turtlebot_arm_object_manipulation/ObjectDetectionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ObjectDetectionResult>)))
  "Returns md5sum for a message object of type '<ObjectDetectionResult>"
  "02736298050f9335208931f532635983")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ObjectDetectionResult)))
  "Returns md5sum for a message object of type 'ObjectDetectionResult"
  "02736298050f9335208931f532635983")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ObjectDetectionResult>)))
  "Returns full string definition for message of type '<ObjectDetectionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# result definition~%~%string[] obj_names~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ObjectDetectionResult)))
  "Returns full string definition for message of type 'ObjectDetectionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# result definition~%~%string[] obj_names~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ObjectDetectionResult>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'obj_names) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4 (cl:length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ObjectDetectionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ObjectDetectionResult
    (cl:cons ':obj_names (obj_names msg))
))
