; Auto-generated. Do not edit!


(cl:in-package turtlebot_arm_object_manipulation-msg)


;//! \htmlinclude ObjectDetectionFeedback.msg.html

(cl:defclass <ObjectDetectionFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ObjectDetectionFeedback (<ObjectDetectionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ObjectDetectionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ObjectDetectionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name turtlebot_arm_object_manipulation-msg:<ObjectDetectionFeedback> is deprecated: use turtlebot_arm_object_manipulation-msg:ObjectDetectionFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ObjectDetectionFeedback>) ostream)
  "Serializes a message object of type '<ObjectDetectionFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ObjectDetectionFeedback>) istream)
  "Deserializes a message object of type '<ObjectDetectionFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ObjectDetectionFeedback>)))
  "Returns string type for a message object of type '<ObjectDetectionFeedback>"
  "turtlebot_arm_object_manipulation/ObjectDetectionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ObjectDetectionFeedback)))
  "Returns string type for a message object of type 'ObjectDetectionFeedback"
  "turtlebot_arm_object_manipulation/ObjectDetectionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ObjectDetectionFeedback>)))
  "Returns md5sum for a message object of type '<ObjectDetectionFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ObjectDetectionFeedback)))
  "Returns md5sum for a message object of type 'ObjectDetectionFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ObjectDetectionFeedback>)))
  "Returns full string definition for message of type '<ObjectDetectionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ObjectDetectionFeedback)))
  "Returns full string definition for message of type 'ObjectDetectionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ObjectDetectionFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ObjectDetectionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ObjectDetectionFeedback
))
