; Auto-generated. Do not edit!


(cl:in-package turtlebot_arm_object_manipulation-msg)


;//! \htmlinclude UserCommandGoal.msg.html

(cl:defclass <UserCommandGoal> (roslisp-msg-protocol:ros-message)
  ((command
    :reader command
    :initarg :command
    :type cl:string
    :initform ""))
)

(cl:defclass UserCommandGoal (<UserCommandGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <UserCommandGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'UserCommandGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name turtlebot_arm_object_manipulation-msg:<UserCommandGoal> is deprecated: use turtlebot_arm_object_manipulation-msg:UserCommandGoal instead.")))

(cl:ensure-generic-function 'command-val :lambda-list '(m))
(cl:defmethod command-val ((m <UserCommandGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader turtlebot_arm_object_manipulation-msg:command-val is deprecated.  Use turtlebot_arm_object_manipulation-msg:command instead.")
  (command m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <UserCommandGoal>) ostream)
  "Serializes a message object of type '<UserCommandGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'command))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'command))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <UserCommandGoal>) istream)
  "Deserializes a message object of type '<UserCommandGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'command) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'command) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<UserCommandGoal>)))
  "Returns string type for a message object of type '<UserCommandGoal>"
  "turtlebot_arm_object_manipulation/UserCommandGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'UserCommandGoal)))
  "Returns string type for a message object of type 'UserCommandGoal"
  "turtlebot_arm_object_manipulation/UserCommandGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<UserCommandGoal>)))
  "Returns md5sum for a message object of type '<UserCommandGoal>"
  "cba5e21e920a3a2b7b375cb65b64cdea")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'UserCommandGoal)))
  "Returns md5sum for a message object of type 'UserCommandGoal"
  "cba5e21e920a3a2b7b375cb65b64cdea")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<UserCommandGoal>)))
  "Returns full string definition for message of type '<UserCommandGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%string command~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'UserCommandGoal)))
  "Returns full string definition for message of type 'UserCommandGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%string command~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <UserCommandGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'command))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <UserCommandGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'UserCommandGoal
    (cl:cons ':command (command msg))
))
